version: '3.8'

services:
  app:
    container_name: tiktok-uploader
    build: .
    depends_on:
      - redis
    networks:
      - appnet
    restart: on-failure:5

  redis:
    container_name: redis
    image: redis:latest
    networks:
      - appnet
    volumes:
      - ../redis-data:/data

networks:
  appnet:
    name: net
    driver: bridge